### ISSUE TITLE
Macro fails to parse executor variable 

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#13]
When I use: 

```rust
graphql_object!(QueryRoot: Arc<Pool> as "Query" |&self| {
    field channel(
        call_sign: String as "The channel's call sign",
        &mut executor
    ) -> FieldResult<Channel>
```

I get the error 

```rust
error: expected ident, found &
  --> src/controller/data.rs:12:9
   |
12 |         &mut executor
   |         ^
```

If I recalled correct @mhallin said he was close to merging a branch where executor could not be mutable so I did the following. 

```rust
    field channel(
        call_sign: String as "The channel's call sign",
        executor
    ) -> FieldResult<Channel> {
```

Which return the error 

```rust
error: no rules expected the token `)`
  --> <juniper macros>:28:70
   |
28 | __graphql__args ! ( @ apply_args , $ reg , $ base , ( $ ( $ rest ) * ) ) } ; (
```

I thought I could cheat it by going 

```
executor: Executor<Arc<Pool>>
```

but it doesn't like that either.

**Comment by zaeleus** [comment]
In >= 0.6.0, the executor var is an immutable reference, e.g., `field channel(&executor, call_sign: String)`. See the first breaking change in [the changelog for 0.6.0](https://github.com/mhallin/juniper/blob/master/CHANGELOG.md#060--2017-01-02).

**Comment by TheServerAsterisk** [comment]
Ahh, okay, I will pay attention to changelog more carefully from now on.
