### ISSUE TITLE
Is there an ability to have a default value for input values? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#28]
According to the specs, one should be able to set a default value as indicated both here [input type spec](http://facebook.github.io/graphql/#sec-The-__InputValue-Type) and [here](https://facebook.github.io/graphql/#sec-Language.Variables). Also, this feature is supported in the js implementation as well as indicated in this [issue](https://github.com/graphql/graphql-js/issues/210). As far I can tell the input macro doesn't allow you specify this so this would be a great feature to have unless of course, it is already there and I am overlooking it.

**Comment by mhallin** [comment]
Do you mean default values on arguments for fields? This is supported; check out the tests here: https://github.com/mhallin/juniper/blob/master/src/macros/tests/args.rs#L46-L54 and the documentation here: https://mhallin.github.io/juniper/juniper/macro.graphql_object!.html#field-arguments

**Comment by TheServerAsterisk** [comment]
That was precisely what I was looking for thanks.

**Comment by TheServerAsterisk** [comment]
@mhallin  Sorry,  it is one-half of what I was looking for I don't this expands to input objects. So for example, 

```
graphql_input_object!(
    pub struct HoursWorked {
        daily_total = 0.0 : f64
    }
)
```

Which I believe should be supported if I am reading the specs correctly.

**Comment by mhallin** [comment]
Huh, no I must have completely missed that feature. I'll try to add it.

**Comment by mhallin** [comment]
The rustdoc hasn't updated yet, but the just-released 0.6.3 version adds default values for input object fields:

```rust
graphql_input_object!(
    struct SampleObject {
        foo = 123: i64 as "A sample field, defaults to 123 if omitted"
    }
);
```

**Comment by TheServerAsterisk** [comment]
The specs aren't really clear on whether a default can only be a basic scalar types or if it can be any type kind. So for example, this currently doesn't work. 
```
enum Color {
    Red,
    Orange,
    Green,
    Blue,
    Black,
    Grey
}

graphql_enum!(Color {
    Color::Red => "RED" as "The color red",
    Color::Orange => "ORANGE",
    Color::Green => "GREEN",
    Color::Blue => "BLUE",
    Color::Grey => "GREY"
    Color::Black => "BLACK" deprecated "Superseded by ORANGE",
});

graphql_input_object!(
    pub struct Room {
         room_color = Color::Grey : Color as "The color of the room defaults to grey"   
    }
);
```

However, I am not 100% certain if it should work due to the wording of the defaultValue clause.

**Comment by TheServerAsterisk** [comment]
I believe this issue also extends to functions which makes it difficult to set defaults for strings which require String::from(), or  "test".to_owned(), etc...

**Comment by mhallin** [comment]
Yeah, due to some syntactical limitations in how the macros work, you need to parenthesize expressions that aren't just a single token tree, e.g. 

```
room_color = (Color::Gray): Color
```

The documentation for release 0.7.0 has been updated with some small examples. That release also contains a fix where input objects couldn't be used as default values.
