### ISSUE TITLE
How to return empty FieldResult? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#29]
Typically for mutation,  I would like to just return a Fieldresult<()>, but () isn't resolvable. In essence, for mutations, I am trying to just return a body on an error and empty body on success, but I can't seem to find how to do this and FieldResult seems to be the most appropriate choice to do so.

**Comment by mhallin** [comment]
I don't think this is possible in GraphQL - there's no "void" type. A common pattern for mutations seem to be to return a boolean field `ok` always set to true.

**Comment by TheServerAsterisk** [comment]
Interesting, I will do that then.
