### ISSUE TITLE
Documentation example for GraphQLType is out of date and doesn't compile

### ISSUE THREAD

**Issue by tupshin** [mhallin/juniper#31]
I tried to take the example at https://mhallin.github.io/juniper/juniper/trait.GraphQLType.html and build it as its own crate. There are a couple of API changes that make it non-compilable, including changing Context to an associated type. After fixing that, though, there are a couple more less obvious fixes, hence the issue, and not a PR.

**Comment by zaeleus** [comment]
The documentation on GitHub Pages is outdated. For now, you can use [the current one hosted on Docs.rs](https://docs.rs/juniper/0.6.3/juniper/) or generate it by cloning the project, running `cargo doc`, and opening `target/doc/juniper/index.html`.

**Comment by mhallin** [comment]
Now that docs.rs has become the central hub for hosted documentation and supports documenting custom features, I've removed the GitHub Pages hosted documentation on mhallin.github.io and pointed the crate metadata to https://docs.rs/juniper.
