### ISSUE TITLE
Update Iron version to 0.5.

### ISSUE THREAD

**Issue by quadrupleslap** [mhallin/juniper#33]

**Comment by Mrmaxmeier** [comment]
This is related to #21 and being addressed in #30.

**Comment by zaeleus** [comment]
The only possible blocker is that juniper [supports the last three versions of Rust](https://github.com/mhallin/juniper/blob/master/.travis.yml#L9-L12). logger 0.3.0 uses the `?` operator, which wasn't [introduced until 1.13](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html). Possible resolutions:

* Submit a patch to logger that replaces `?` usage with `try!`.
* Remove logger from the server example.
* Wait until the next version of Rust to bump the minimum supported Rust version. 1.16 should be out on March 16.
* Drop support for Rust 1.12 now.

**Comment by mhallin** [comment]
Yeah, I think we'll drop 1.12 for now if our dependencies start requiring more recent versions. The older versions were put there mostly in order to not _accidentally_ break support for older Rusts; not all people upgrade to the latest compiler immediately as they get released.

**Comment by mhallin** [comment]
Release 0.7.0 with the `iron-handlers` feature now depends on Iron 0.5.
