### ISSUE TITLE
Drop rustc-serialize support

### ISSUE THREAD

**Issue by dtolnay** [mhallin/juniper#36]
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.

This would be a good time to let us know if there is any functionality you require from Serde before that happens.

**Comment by theduke** [comment]
If @mhallin  is interested, I could work on a PR for removing rustc-serialize support from the next release.

**Comment by TheServerAsterisk** [comment]
@theduke  Sorry, but I stole this out from underneath you :stuck_out_tongue_closed_eyes: as I am trying to remove the duplicate code I most likely need to write for #40 if both rustc_serialization and serde were supported.

**Comment by theduke** [comment]
I... I ... !

Well. 
I think I'll survive.

:joy:

**Comment by theduke** [comment]
Ok, I'm over it. :joy:
