### ISSUE TITLE
Rocket Integration

### ISSUE THREAD

**Issue by theduke** [mhallin/juniper#39]
I'm working on integration into [Rocket](http://rocket.rs).

Would you be interested in a PR that adds a Rocket handler under a feature flag?

**Comment by mhallin** [comment]
Definitely! On the non-async side of Rust web programming, Rocket seems to be really .. lifting off?

**Comment by theduke** [comment]
> Rocket seems to be really .. lifting off?

I see what you did there. ;)

**Comment by stankec** [comment]
Hey!

I've made a response handler for Rocket that integrates with Juniper. It's available [here](https://github.com/stankec/stanko.io/blob/master/src/graphql/request.rs) and can be used like [this](https://github.com/stankec/stanko.io/blob/master/src/main.rs#L40).

Was the integration you are talking about imagined in a similar fashion? Would you be interested in a PR from this?

**Comment by mhallin** [comment]
Nice!

I used that example and some work put into the Iron integration to come up with a rudimentary integration. You can see the example server here: https://github.com/mhallin/juniper/blob/master/examples/rocket-server.rs. This would be the Rocket-specific code you as an application developer would have to write.

I'm a bit annoyed by the fact that you have to make separate functions for the GET and POST routes, and that `GET /graphql` returns 404 unless we add yet another route. It _would_ be possible to create `Route` instances directly, but then it would be harder to provide custom `State<>` objects to the GraphQL context for e.g. database access.

Unless I'm missing something, this will probably be the integration that I'll release in the next version.

**Comment by stankec** [comment]
Looks great.

When will this be released?

**Comment by stankec** [comment]
@mhallin just saw the release. I thin this can be closed now.
