### ISSUE TITLE
example doesn't work?

### ISSUE THREAD

**Issue by RossRogers** [mhallin/juniper#45]
Hello,
I'm trying to do your simple iron integration example using `https://github.com/mhallin/juniper/blob/master/examples/server.rs` and these dependencies:

```
[dependencies]
iron = "^0.5.1"
juniper = { version="0.7.0", features = ["iron-handlers"] }
rustc-serialize = "^0.3.19"
serde = "^0.9.1"
router = "^0.5.0"
mount = "^0.3.0"
logger = "^0.3.0"
iron-test = "^0.5.0"
bencher = "^0.1.2"
```

What I get from `cargo build` is:
```
error[E0432]: unresolved import `juniper::tests::model::Database`
  --> src/main.rs:14:5
   |
14 | use juniper::tests::model::Database;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `tests` in `juniper`

error: aborting due to previous error

error: Could not compile `hello_world`.
```

Is there a simple juniper, iron, mysql/postgresql hello world repo out there that can just run so I can do a GraphQL hello world?  How can I make the sample do something?

**Comment by TheServerAsterisk** [comment]
You can run the example server by using the following cargo command: 

```
cargo run --example server --features "iron-handlers expose-test-schema"
```

This should make the iron instance listen on 0.0.0.0:8000

**Comment by RossRogers** [comment]
Ok, it runs with that magical string :-)  

How about talking to an actual database like MySQL or Postgresql or even sqlite (yeah its real too...)?  Is there an example?  If so, can you guys make a starter repo for newbs? This setup with graphql is the first time I can find a non-toy usage case and dip my toe into Rust.

**Comment by mhallin** [comment]
Yeah, running the example requires a bit of undocumented magic :) I've been waiting for Cargo to support declaring features per example in Cargo.toml, and it looks like it maybe is supported now. I'll see if I can make it so that you don't need to specify the required features manually.

Regarding a bigger example; I've been using Juniper in another project with a PostgreSQL backend. I'll try to extract the interesting parts and put them somewhere public.

**Comment by stankec** [comment]
Hey @RossRogers ! 

Regarding the DB example. I've started working on a blog-like app that's [publically available](https://github.com/stankec/stanko.io), it's very much a work in progress, but it has what you are looking for - integration with Juniper, Diesel (Postgres ORM) and Rocket (though not fully, variable passing doesn't work yet - waiting for serde support on Juniper's side). 

Hope this helps.

**Comment by TheServerAsterisk** [comment]
@RossRogers Also, you might want to check out #5 where I bombarded @mhallin with a bunch of basic questions.

**Comment by RossRogers** [comment]
Thanks for this contribution, @stankec .  Personally, I'm really looking for a [Django Rest Framework](http://www.django-rest-framework.org/) analogue.  A purely machine oriented back-end API system with perhaps the ability to browse it in order to discover the features. I.E. a bare-bones graphql request interpreter that talks to a database.  Something that I can immediately start tinkering with to understand the system and peel the onion.

**Comment by RossRogers** [comment]
@mhallin, 
Any chance you could dash off an iron, juniper, and diesel repo?  Yes, I am newbie to rust and cargo.  I just want to say "hello world" with some sort of complete example that talks to a real database.

**Comment by mhallin** [comment]
I opened a small sample repository at https://github.com/mhallin/juniper-example-todo-backend, with some basic operations to add/update/list todo items a la Todo-Backend. It uses SQLite, but given that Diesel is fairly backend agnostic, it shouldn't be hard to just replace everything there with e.g. Postgres.

I plan to add some more features as well, but that will probably be another repo - I'll keep this one simple to make it easy to understand the basics.

Please have a look and let me know if it's missing something :)

**Comment by RossRogers** [comment]
Thank you!  I had given up on this...  Spent a month messing around with the system here and there and was going to revert to Django Rest Framework.  I shall dive in again.

**Comment by RossRogers** [comment]
@mhallin , Any chance you can expand that example a bit to do a more complex schema?  Datetimes, nullable datetimes, one-to-one foreign keys, on to many foreign keys ?  I'm a rube.

**Comment by KamuelaFranco** [comment]
How do I get the equivalent working with the Rocket example? `cargo run --example server --features "iron-handlers expose-test-schema"`, probably for reasons obvious to a better-trained eye, doesn't solve the inability to run the example for me.
