### ISSUE TITLE
How do I batch queries?

### ISSUE THREAD

**Issue by rushmorem** [mhallin/juniper#46]
Instead of sending queries to a database cluster one by one, I would like to batch them instead and send just one query. Is this possible?

**Comment by TheServerAsterisk** [comment]
You can use field alias to batch your queries. For example, you can do:

```js
query {
  human_batch:human(id: "1001"){
    id,
    name,
    homePlanet
  }
  droid_batch:droid(id: "2001"){
    id,
    name,
    primaryFunction
  }
}
```

**Comment by rushmorem** [comment]
Thank you. Let me try that. I'm knew to both GraphQL and Juniper so please pardon my ignorance :smile:
