### ISSUE TITLE
Query Variables Will Panic When Parsing An Optional Object

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#49]
To reproduce the issue you can use the patch found in this [gist](https://gist.github.com/TheServerAsterisk/2ef0f7b6f7013d9792d5550d1be34112). Which slightly alters the test schema. 

Which changes the database schema with a new graphql input object. 
```rust 
graphql_input_object!(
    pub struct TestSearch {
        episode: Option<Episode>,
        meaningless_value: Option<Vec<i64>>
    }
);

graphql_object!(Database: Database as "Query" |&self| {
    description: "The root query object of the schema"
    ...
    field hero(
        search_input: Option<TestSearch> as
        "If omitted, returns the hero of the whole saga. If provided, returns \
        the hero of that particular episode",
    ) -> Option<&Character> {
        if let Some(search_input) = search_input {
            Some(self.get_hero(search_input.episode).as_character())
        } else {
            None
        }
    }
});

```

The following query will produce a panic: 
```js
query($test: TestSearch) {
  hero(searchInput: $test){
    id,
    name,
    appearsIn
  }
}
```
With the query variable `$test` as: 
```json
{
  "test": {
    "episode": "NEW_HOPE",
    "meaninglessValue": [1,2]
  }
}
```
This does work 
```js
query {
  hero(
    searchInput:{
    	episode: NEW_HOPE,
    	meaninglessValue: [1,2]
  	}
  ){
    id,
    name,
    appearsIn
  }
}
```
Unless my lack of sleep is catching up to me both of these queries should work. It appears that is failing somewhere in the graphql input macro.

Unfortunately, I am not 100% the actually cause of the error be it somewhere in the iron-handler or somewhere later. I'll update if I find any more information.

**Comment by TheServerAsterisk** [comment]
For those who want a partial fix change 

```
    fn visit_u64<E>(self, value: u64) -> Result<InputValue, E>
                where E: de::Error,
            {
                if value > i64::max_value() as u64 {
                    self.visit_f64(value as f64)
                } else {
                    self.visit_i64(value as i64)
                }
            }
```

However, I am still trying to figure out why the f64 get converted into a None which is the cause of my issue.

**Comment by mhallin** [comment]
I found two problems. First, the serde integration was always constructing `InputValue::Float` instances from positive integers, which can't be coerced to integer types (per the spec). Second, scalar values were not validated before execution started.

Both issues have been fixed and will be resolved in the next release.
