### ISSUE TITLE
Stricter Enforcement Of Int Types

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#52]
Currently, if one wanted to they could go beyond the  -(2^31) to 2^31 -1 integer range if they used an i64 as an argument. However, the range for an i32 needs to be enforced in order to meet the specs. Also, it ensures that individuals don't accidentally receive a 64 bit integer even though js represents ints as doubles. Which is fine until you get integers larger than 2^53 or less than -2^53. 

Based upon the swapi example one would expect the following error message if you say used 2147483648 as an int. 

` "Argument \"first\" has invalid value 2147483648.\nExpected type \"Int\", found 2147483648."`

**Comment by mhallin** [comment]
Yeah, I think I made a mistake using `i64` as the basic integer type in the beginning. Replacing `i64` with `i32` is unfortunately a breaking change, but sending 64 bit integers over JSON, especially with JavaScript clients is pretty dangerous.

I've pushed some code that replaces 64 with 32 bit integers in general in Juniper, and added guards that will fail to construct `InputValue` instances from too big integral numbers. This means that the next release will break client code :(

**Comment by brandur** [comment]
I love how strictly correct the project is, but is there any recommended workaround to be able to generate numbers that are larger than i32’s bounds.

In practice if you’re using something like i64 for an object identifier, you’re never going to run out of runway. i32 on the other hand is fairly easy to find the limits of, and a considerable number of applications will get there (I’ve personally brushed up against this a few times now with some pain as we then scrambled to find a workaround).

Even JS’ limit of 2^53 would be quite a bit better if there’s a sane way to make that happen.

**Comment by brandur** [comment]
Actually, now that I think about this a little more, it shouldn't be too bad to just expose integer IDs as strings — clients should mostly be treating them as opaque tokens anyway.
