### ISSUE TITLE
Generate Table / Objects at run time

### ISSUE THREAD

**Issue by siscia** [mhallin/juniper#53]
Hi,

I tried to look into the code but I didn't come up with a definitive answer.

I am wondering if is possible to generate classes of objects at run time.

What I want to do is to use juniper to build a SQL wrapper giving the user the possibility to create, not only new rows but also new tables at run time. Is it clear?

It is possible with juniper?

Thanks

**Comment by mhallin** [comment]
If you mean creating new GraphQL object types at runtime, the answer is practically "no". While it would be possible, you would not gain anything from using Juniper. This was briefly discussed in https://github.com/mhallin/juniper/issues/7.

**Comment by siscia** [comment]
Ok thank you :)
